// Code generated by "stringer -type state -trimprefix state"; DO NOT EDIT.

package retcon

import "strconv"

const _state_name = "UnknownAnalyzingCleanDirty"

var _state_index = [...]uint8{0, 7, 16, 21, 26}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
